### ISSUE TITLE
Pedidos de trabajo--> no cambia al estado finalizado

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#12]
v2.1.4.4

Descripción:
El pedido 167, paso por el proceso de evaluación de viabilidad y se rechazó. Si bien la misma ya no aparece en la bandeja de tareas, cuando se lo busca en el detalle del listado de pedidos de trabajo el mismo aparece con estado "En curso" cuando **debería quedar con estado "Finalizado"**

![image](https://user-images.githubusercontent.com/87376576/186724346-16074094-e0e0-4ad5-9bc9-4988476cc2d6.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.6
