### ISSUE TITLE
Tareas--> Viabilidad de cotización: Agregar alert de rechazo

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#14]
v 2.1.4.4

Descripción:
Si se rechaza y se presiona el botón hecho, el sistema muestra un carte de guardado exitoso, cuando debería emitir un alert de confirmación, si el mismo se acepta,la tarea pasará al estado “Rechazado”. Seguidamente, envía una notificación al cliente vía email, avisando que no se avanzará con la cotización. 

![image](https://user-images.githubusercontent.com/87376576/186738022-8ba1881b-d9bd-4af0-bab8-40b65229a9a1.png)

Maqueta:
![image](https://user-images.githubusercontent.com/87376576/186738247-3994b6f7-6408-46b3-9305-5a93c3318b12.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.6
