### ISSUE TITLE
Tareas--> Cambiar nombre de estados en tabla

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#18]
Ambiente TEST v2.1.4.9

Descripción:
La tabla deberia ser estados_seinCONTRATADA

![image](https://user-images.githubusercontent.com/87376576/190720264-7335a751-7d6e-41a2-a730-bcae4ec88705.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.6
