### ISSUE TITLE
Tareas-->Pedido de trabajo: al finalizar el proceso, no aparece el pedido finalizado en la bandeja de pedidos de trabajo

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#31]
Ambiente TEST v2.1.4.9

Descripción:

El case 23006 desapareció de la bandeja de pedido de trabajos

![image](https://user-images.githubusercontent.com/87376576/190798317-49ed6dab-de5d-4da9-92af-5d4f459c52bb.png)

![image](https://user-images.githubusercontent.com/87376576/190798866-e3c79cb1-bc4d-4be1-83db-a9a58ad8d86d.png)

**Comment by floto-trazalog** [comment]
En ambiente test - v2.1.5
Si aparece el pedido entregado en la bandeja de pedidos de trabajo. **Sugerencia:** que muestre el estado como "Finalizado"


![image](https://user-images.githubusercontent.com/88331456/192811446-f8960a22-3f51-445a-a4fb-2eff63d6ab34.png)

**Comment by floto-trazalog** [comment]
Solucionado en ambiente test -  v2.1.6 
Se corrige el estado a modo "Entregado" | Solucionado!
