### ISSUE TITLE
Tareas-->Paletizar y Despachar: agregar campo fecha cambiarle nombre, agregar máscara date y ocultar url de token

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#32]
v 2.1.4.11

Descripción:

- En el campo de fecha cambiar nombre del label a "Fecha de entrega". Nota: este valor es el que se debe utilizar en el paso siguiente (generar QR). 
- Agregar máscara date al campo Fecha de entrega.
- Ocultar la url del token

![image](https://user-images.githubusercontent.com/87376576/191040607-1fff4401-0c16-4896-ae49-7ffaf6a0427e.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.9.2
