### ISSUE TITLE
Tareas--> Cotización de trabajo: pintar/mover el botón agregar y agregar función guardar al botón hecho

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#33]
v 2.1.4.12 - Ambiente Test

Descripción:

1. Además, el botón de agregar esta escondido y desalineado, correrlo hacia la derecha y dejarlo de color verde.
2. En pantalla de cotización de trabajo, el botón "Guardar" unificarlo con el botón Hecho.

![image](https://user-images.githubusercontent.com/87376576/191605488-57f045ce-1fa9-4398-9a00-2790ce85103f.png)

**Comment by floto-trazalog** [comment]
Solucionado en test - v2.1.5
