### ISSUE TITLE
Tareas--> reevaluar pedido de cotización: error de tipeo

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/sein-tools-almpantar#9]
v 2.1.4.3

Descripción:
corregir la palabra "Realizar"

![image](https://user-images.githubusercontent.com/87376576/185957119-94a58ac1-d9e8-49bf-96d8-95ca98c90f07.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.5
